=== ChristopherRabotin/GMAT/apache/xerces-c-3.2.3/tools/IANACharset/charset.dtd
<?xml version="1.0" encoding="US-ASCII" ?>

<!ELEMENT   Encoding (#PCDATA)>
<!ATTLIST   Encoding
            name     CDATA #REQUIRED>

<!ELEMENT   Charset  (Encoding+)>

=== ChristopherRabotin/GMAT/apache/xerces-c-3.2.3/tools/IANACharset/IANACharsetList.xml
<?xml version='1.0' encoding='utf-8' ?>
<!DOCTYPE Charset SYSTEM 'charset.dtd'>
<Charset>
    <Encoding name="ANSI_X3.4-1968"/>
    <Encoding name="iso-ir-6"/>
    <Encoding name="ANSI_X3.4-1986"/>
    <Encoding name="ISO_646.irv:1991"/>
    <Encoding name="ASCII"/>
    <Encoding name="ISO646-US"/>
    <Encoding name="US-ASCII"/>
    <Encoding name="us"/>
    <Encoding name="IBM367"/>
    <Encoding name="cp367"/>
    <Encoding name="csASCII"/>
    <Encoding name="ISO-10646-UTF-1"/>
    <Encoding name="csISO10646UTF1"/>
    <Encoding name="ISO_646.basic:1983"/>
    <Encoding name="ref"/>
    <Encoding name="csISO646basic1983"/>
    <Encoding name="INVARIANT"/>
    <Encoding name="csINVARIANT"/>
    <Encoding name="ISO_646.irv:1983"/>
    <Encoding name="iso-ir-2"/>
    <Encoding name="irv"/>
    <Encoding name="csISO2IntlRefVersion"/>
    <Encoding name="BS_4730"/>
    <Encoding name="iso-ir-4"/>
    <Encoding name="ISO646-GB"/>
    <Encoding name="gb"/>
    <Encoding name="uk"/>
    <Encoding name="csISO4UnitedKingdom"/>
    <Encoding name="NATS-SEFI"/>
    <Encoding name="iso-ir-8-1"/>
    <Encoding name="csNATSSEFI"/>
    <Encoding name="NATS-SEFI-ADD"/>
    <Encoding name="iso-ir-8-2"/>
    <Encoding name="csNATSSEFIADD"/>
    <Encoding name="NATS-DANO"/>
    <Encoding name="iso-ir-9-1"/>
    <Encoding name="csNATSDANO"/>
    <Encoding name="NATS-DANO-ADD"/>
    <Encoding name="iso-ir-9-2"/>
    <Encoding name="csNATSDANOADD"/>
    <Encoding name="SEN_850200_B"/>
    <Encoding name="iso-ir-10"/>
    <Encoding name="FI"/>
    <Encoding name="ISO646-FI"/>
    <Encoding name="ISO646-SE"/>
    <Encoding name="se"/>
    <Encoding name="csISO10Swedish"/>
    <Encoding name="SEN_850200_C"/>
    <Encoding name="iso-ir-11"/>
    <Encoding name="ISO646-SE2"/>
    <Encoding name="se2"/>
    <Encoding name="csISO11SwedishForNames"/>
    <Encoding name="KS_C_5601-1987"/>
    <Encoding name="iso-ir-149"/>
    <Encoding name="KS_C_5601-1989"/>
    <Encoding name="KSC_5601"/>
    <Encoding name="korean"/>
    <Encoding name="csKSC56011987"/>
    <Encoding name="ISO-2022-KR"/>
    <Encoding name="csISO2022KR"/>
    <Encoding name="EUC-KR"/>
    <Encoding name="csEUCKR"/>
    <Encoding name="ISO-2022-JP"/>
    <Encoding name="csISO2022JP"/>
    <Encoding name="ISO-2022-JP-2"/>
    <Encoding name="csISO2022JP2"/>
    <Encoding name="ISO-2022-CN"/>
    <Encoding name="ISO-2022-CN-EXT"/>
    <Encoding name="JIS_C6220-1969-jp"/>
    <Encoding name="JIS_C6220-1969"/>
    <Encoding name="iso-ir-13"/>
    <Encoding name="katakana"/>
    <Encoding name="x0201-7"/>
    <Encoding name="csISO13JISC6220jp"/>
    <Encoding name="JIS_C6220-1969-ro"/>
    <Encoding name="iso-ir-14"/>
    <Encoding name="jp"/>
    <Encoding name="ISO646-JP"/>
    <Encoding name="csISO14JISC6220ro"/>
    <Encoding name="IT"/>
    <Encoding name="iso-ir-15"/>
    <Encoding name="ISO646-IT"/>
    <Encoding name="csISO15Italian"/>
    <Encoding name="PT"/>
    <Encoding name="iso-ir-16"/>
    <Encoding name="ISO646-PT"/>
    <Encoding name="csISO16Portuguese"/>
    <Encoding name="ES"/>
    <Encoding name="iso-ir-17"/>
    <Encoding name="ISO646-ES"/>
    <Encoding name="csISO17Spanish"/>
    <Encoding name="greek7-old"/>
    <Encoding name="iso-ir-18"/>
    <Encoding name="csISO18Greek7Old"/>
    <Encoding name="latin-greek"/>
    <Encoding name="iso-ir-19"/>
    <Encoding name="csISO19LatinGreek"/>
    <Encoding name="DIN_66003"/>
    <Encoding name="iso-ir-21"/>
    <Encoding name="de"/>
    <Encoding name="ISO646-DE"/>
    <Encoding name="csISO21German"/>
    <Encoding name="NF_Z_62-010_(1973)"/>
    <Encoding name="iso-ir-25"/>
    <Encoding name="ISO646-FR1"/>
    <Encoding name="csISO25French"/>
    <Encoding name="Latin-greek-1"/>
    <Encoding name="iso-ir-27"/>
    <Encoding name="csISO27LatinGreek1"/>
    <Encoding name="ISO_5427"/>
    <Encoding name="iso-ir-37"/>
    <Encoding name="csISO5427Cyrillic"/>
    <Encoding name="JIS_C6226-1978"/>
    <Encoding name="iso-ir-42"/>
    <Encoding name="csISO42JISC62261978"/>
    <Encoding name="BS_viewdata"/>
    <Encoding name="iso-ir-47"/>
    <Encoding name="csISO47BSViewdata"/>
    <Encoding name="INIS"/>
    <Encoding name="iso-ir-49"/>
    <Encoding name="csISO49INIS"/>
    <Encoding name="INIS-8"/>
    <Encoding name="iso-ir-50"/>
    <Encoding name="csISO50INIS8"/>
    <Encoding name="INIS-cyrillic"/>
    <Encoding name="iso-ir-51"/>
    <Encoding name="csISO51INISCyrillic"/>
    <Encoding name="ISO_5427:1981"/>
    <Encoding name="iso-ir-54"/>
    <Encoding name="ISO5427Cyrillic1981"/>
    <Encoding name="ISO_5428:1980"/>
    <Encoding name="iso-ir-55"/>
    <Encoding name="csISO5428Greek"/>
    <Encoding name="GB_1988-80"/>
    <Encoding name="iso-ir-57"/>
    <Encoding name="cn"/>
    <Encoding name="ISO646-CN"/>
    <Encoding name="csISO57GB1988"/>
    <Encoding name="GB_2312-80"/>
    <Encoding name="iso-ir-58"/>
    <Encoding name="chinese"/>
    <Encoding name="csISO58GB231280"/>
    <Encoding name="NS_4551-1"/>
    <Encoding name="iso-ir-60"/>
    <Encoding name="ISO646-NO"/>
    <Encoding name="no"/>
    <Encoding name="csISO60DanishNorwegian"/>
    <Encoding name="csISO60Norwegian1"/>
    <Encoding name="NS_4551-2"/>
    <Encoding name="ISO646-NO2"/>
    <Encoding name="iso-ir-61"/>
    <Encoding name="no2"/>
    <Encoding name="csISO61Norwegian2"/>
    <Encoding name="NF_Z_62-010"/>
    <Encoding name="iso-ir-69"/>
    <Encoding name="ISO646-FR"/>
    <Encoding name="fr"/>
    <Encoding name="csISO69French"/>
    <Encoding name="videotex-suppl"/>
    <Encoding name="iso-ir-70"/>
    <Encoding name="csISO70VideotexSupp1"/>
    <Encoding name="PT2"/>
    <Encoding name="iso-ir-84"/>
    <Encoding name="ISO646-PT2"/>
    <Encoding name="csISO84Portuguese2"/>
    <Encoding name="ES2"/>
    <Encoding name="iso-ir-85"/>
    <Encoding name="ISO646-ES2"/>
    <Encoding name="csISO85Spanish2"/>
    <Encoding name="MSZ_7795.3"/>
    <Encoding name="iso-ir-86"/>
    <Encoding name="ISO646-HU"/>
    <Encoding name="hu"/>
    <Encoding name="csISO86Hungarian"/>
    <Encoding name="JIS_C6226-1983"/>
    <Encoding name="iso-ir-87"/>
    <Encoding name="x0208"/>
    <Encoding name="JIS_X0208-1983"/>
    <Encoding name="csISO87JISX0208"/>
    <Encoding name="greek7"/>
    <Encoding name="iso-ir-88"/>
    <Encoding name="csISO88Greek7"/>
    <Encoding name="ASMO_449"/>
    <Encoding name="ISO_9036"/>
    <Encoding name="arabic7"/>
    <Encoding name="iso-ir-89"/>
    <Encoding name="csISO89ASMO449"/>
    <Encoding name="iso-ir-90"/>
    <Encoding name="csISO90"/>
    <Encoding name="JIS_C6229-1984-a"/>
    <Encoding name="iso-ir-91"/>
    <Encoding name="jp-ocr-a"/>
    <Encoding name="csISO91JISC62291984a"/>
    <Encoding name="JIS_C6229-1984-b"/>
    <Encoding name="iso-ir-92"/>
    <Encoding name="ISO646-JP-OCR-B"/>
    <Encoding name="jp-ocr-b"/>
    <Encoding name="csISO92JISC62991984b"/>
    <Encoding name="JIS_C6229-1984-b-add"/>
    <Encoding name="iso-ir-93"/>
    <Encoding name="jp-ocr-b-add"/>
    <Encoding name="csISO93JIS62291984badd"/>
    <Encoding name="JIS_C6229-1984-hand"/>
    <Encoding name="iso-ir-94"/>
    <Encoding name="jp-ocr-hand"/>
    <Encoding name="csISO94JIS62291984hand"/>
    <Encoding name="JIS_C6229-1984-hand-add"/>
    <Encoding name="iso-ir-95"/>
    <Encoding name="jp-ocr-hand-add"/>
    <Encoding name="csISO95JIS62291984handadd"/>
    <Encoding name="JIS_C6229-1984-kana"/>
    <Encoding name="iso-ir-96"/>
    <Encoding name="csISO96JISC62291984kana"/>
    <Encoding name="ISO_2033-1983"/>
    <Encoding name="iso-ir-98"/>
    <Encoding name="e13b"/>
    <Encoding name="csISO2033"/>
    <Encoding name="ANSI_X3.110-1983"/>
    <Encoding name="iso-ir-99"/>
    <Encoding name="CSA_T500-1983"/>
    <Encoding name="NAPLPS"/>
    <Encoding name="csISO99NAPLPS"/>
    <Encoding name="ISO_8859-1:1987"/>
    <Encoding name="iso-ir-100"/>
    <Encoding name="ISO_8859-1"/>
    <Encoding name="ISO-8859-1"/>
    <Encoding name="latin1"/>
    <Encoding name="l1"/>
    <Encoding name="IBM819"/>
    <Encoding name="CP819"/>
    <Encoding name="csISOLatin1"/>
    <Encoding name="ISO_8859-2:1987"/>
    <Encoding name="iso-ir-101"/>
    <Encoding name="ISO_8859-2"/>
    <Encoding name="ISO-8859-2"/>
    <Encoding name="latin2"/>
    <Encoding name="l2"/>
    <Encoding name="csISOLatin2"/>
    <Encoding name="T.61-7bit"/>
    <Encoding name="iso-ir-102"/>
    <Encoding name="csISO102T617bit"/>
    <Encoding name="T.61-8bit"/>
    <Encoding name="T.61"/>
    <Encoding name="iso-ir-103"/>
    <Encoding name="csISO103T618bit"/>
    <Encoding name="ISO_8859-3:1988"/>
    <Encoding name="iso-ir-109"/>
    <Encoding name="ISO_8859-3"/>
    <Encoding name="ISO-8859-3"/>
    <Encoding name="latin3"/>
    <Encoding name="l3"/>
    <Encoding name="csISOLatin3"/>
    <Encoding name="ISO_8859-4:1988"/>
    <Encoding name="iso-ir-110"/>
    <Encoding name="ISO_8859-4"/>
    <Encoding name="ISO-8859-4"/>
    <Encoding name="latin4"/>
    <Encoding name="l4"/>
    <Encoding name="csISOLatin4"/>
    <Encoding name="ECMA-cyrillic"/>
    <Encoding name="iso-ir-111"/>
    <Encoding name="csISO111ECMACyrillic"/>
    <Encoding name="CSA_Z243.4-1985-1"/>
    <Encoding name="iso-ir-121"/>
    <Encoding name="ISO646-CA"/>
    <Encoding name="csa7-1"/>
    <Encoding name="ca"/>
    <Encoding name="csISO121Canadian1"/>
    <Encoding name="CSA_Z243.4-1985-2"/>
    <Encoding name="iso-ir-122"/>
    <Encoding name="ISO646-CA2"/>
    <Encoding name="csa7-2"/>
    <Encoding name="csISO122Canadian2"/>
    <Encoding name="CSA_Z243.4-1985-gr"/>
    <Encoding name="iso-ir-123"/>
    <Encoding name="csISO123CSAZ24341985gr"/>
    <Encoding name="ISO_8859-6:1987"/>
    <Encoding name="iso-ir-127"/>
    <Encoding name="ISO_8859-6"/>
    <Encoding name="ISO-8859-6"/>
    <Encoding name="ECMA-114"/>
    <Encoding name="ASMO-708"/>
    <Encoding name="arabic"/>
    <Encoding name="csISOLatinArabic"/>
